### ISSUE TITLE
CER results very low

### ISSUE THREAD

**Issue by fox-gamer** [domainxz/top-k-rec#13]
Hello,

Using the code and data (fold 0) present in this repository the following cer's performance with meta content feature is obtained:
im,0.010786,0.023110,0.038238,0.056547,0.077417,0.099598
om,0.038770,0.049797,0.060419,0.069602,0.078098,0.085790

Could you please advice which parameters should be changed to obtain considerably higher results since changing (max_iter=20) to (max_iter=200) produces similar results as above?

Thanks in advance

**Comment by domainxz** [comment]
> Hello,
> 
> Using the code and data (fold 0) present in this repository the following cer's performance with meta content feature is obtained:
> im,0.010786,0.023110,0.038238,0.056547,0.077417,0.099598
> om,0.038770,0.049797,0.060419,0.069602,0.078098,0.085790
> 
> Could you please advice which parameters should be changed to obtain considerably higher results since changing (max_iter=20) to (max_iter=200) produces similar results as above?
> 
> Thanks in advance

Hi, thank you for the valuable feedback.
This was caused by a reference bug.
I have fixed it in cer.py.
Please try it again.
