### ISSUE TITLE
train.py最后一行是不是有点问题

### ISSUE THREAD

**Issue by songiu** [domainxz/top-k-rec#3]
model = CER(k=50, d=20000);
model.load_train_data('data/uid', 'data/vid', 'data/f0tr.txt');
model.load_content_data('data/meta.pkl', 'data/vid');
model.train('embed/cer', max_iter=200)

model = DPM(k=50, d=20000);
model.load_train_data('data/uid', 'data/vid', 'data/f0tr.txt');
model.load_content_data('data/meta.pkl', 'data/vid');
model.train('embed/cer', max_iter=200)

最后一行'embed/cer'这里是不是有点问题，是不是应该写成
model.train('embed/dpm', max_iter=200)

**Comment by domainxz** [comment]
Yes, you are right. I will change it later.

**Comment by domainxz** [comment]
> 
> 
> model = CER(k=50, d=20000);
> model.load_train_data('data/uid', 'data/vid', 'data/f0tr.txt');
> model.load_content_data('data/meta.pkl', 'data/vid');
> model.train('embed/cer', max_iter=200)
> 
> model = DPM(k=50, d=20000);
> model.load_train_data('data/uid', 'data/vid', 'data/f0tr.txt');
> model.load_content_data('data/meta.pkl', 'data/vid');
> model.train('embed/cer', max_iter=200)
> 
> 最后一行'embed/cer'这里是不是有点问题，是不是应该写成
> model.train('embed/dpm', max_iter=200)

Yes, you are right. I will change it later.
