### ISSUE TITLE
The original 10380 videos download link is down

### ISSUE THREAD

**Issue by fox-gamer** [domainxz/top-k-rec#4]
Hello,

Could you re-upload the 10380 videos since http://pan.baidu.com/s/1jIDdAwI is down.

Thanks in advance

**Comment by domainxz** [comment]
> Hello,
> 
> Could you re-upload the 10380 videos since http://pan.baidu.com/s/1jIDdAwI is down.
> 
> Thanks in advance

The link was cancelled because the host website change the share link format.
The new link is https://pan.baidu.com/s/1SC3pWVMyQkqHGa9bZpi3zA.
The access code is ny8e.

**Comment by fox-gamer** [comment]
When I access the new link I get this message "此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！", could you fix it please?

Thanks in advance

**Comment by domainxz** [comment]
> When I access the new link I get this message "此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！", could you fix it please?
> 
> Thanks in advance

I will use another platform to host videos. Please wait.
