### ISSUE TITLE
Content shared by the new link is not accessible!

### ISSUE THREAD

**Issue by fox-gamer** [domainxz/top-k-rec#5]
Hello,

The content shared by the new link "https://pan.baidu.com/s/1SC3pWVMyQkqHGa9bZpi3zA" is not accessible, could you fix it please? 

Thanks in advance

**Comment by domainxz** [comment]
> 
> 
> Hello,
> 
> The content shared by the new link "https://pan.baidu.com/s/1SC3pWVMyQkqHGa9bZpi3zA" is not accessible, could you fix it please?
> 
> Thanks in advance

Hi, I have changed my link to google drive. This should be fine now.
